package ru;// Generated by Selenium IDE

import org.junit.Test;
public class GroupDeletionTest extends TestBase {

  @Test
  public void testGroupDeletion() {
    goToGroupsPage();
    selectGroup();
    getDelete();
   returnToGroupPage();
  }


}
