package ru;// Generated by Selenium IDE

import org.junit.Test;

public class GroupCreationTest extends TestBase{

    @Test
    public void testGroupCreation() {

        goToGroupsPage();
        initGroupCreation();
        fillFormGroup(new GroupData("test1", "test2", "test3"));
        submitGroupCreation("submit");
        returnToGroupPage();
    }

}
