package ru.tests;// Generated by Selenium IDE

import org.junit.Test;

public class GroupDeletionTest extends TestBase {

    @Test
    public void testGroupDeletion() {
        app.getNavigationHelper().goToGroupsPage();
        app.getGroupHelper().selectGroup();
        app.getGroupHelper().getDelete();
        app.getGroupHelper().returnToGroupPage();
    }
}
